### ISSUE TITLE
when i start it then it shows pause and then shutdowns once i press any key

### ISSUE THREAD

**Issue by BabixzRayan** [XtramCZ/auto-advertise-py#1]
![image](https://github.com/XtramCZ/auto-advertise-py/assets/93261423/24e538c1-9d8e-483e-96d9-0ec17ca86a78)

**Comment by XtramCZ** [comment]
Hey, how did you install python? Does it react to "py", "python" or "python3" commands in the terminal?

**Comment by BabixzRayan** [comment]
it was working a few days ago now suddenly it comes like that

**Comment by XtramCZ** [comment]
Since you did not answer my previous question about specific python version, try them all manually if they work:
- `py main.py`
or
- `python main.py`
or
- `python3 main.py`

You can also try to: redownload the script, check the config on an online yaml checker, run it with admin perms (unlikely), or try the nodejs version here https://github.com/XtramCZ/auto-advertise-js

**Comment by BabixzRayan** [comment]
I installed python from the Microsoft Store

**Comment by XtramCZ** [comment]
try reinstalling it from https://python.org

**Comment by BabixzRayan** [comment]
![image](https://github.com/XtramCZ/auto-advertise-py/assets/93261423/7984c27b-b1ad-4144-a98d-45c69364589d)

**Comment by BabixzRayan** [comment]
![image](https://github.com/XtramCZ/auto-advertise-py/assets/93261423/7d51097e-401d-4aa5-bfbe-b5acd40f0d42)

**Comment by XtramCZ** [comment]
Try with different token, otherwise you can set your ID manually by changing line 147 to `user_id = "<your id>"`

**Comment by BabixzRayan** [comment]
works when i updated the token. thanks!
